OrdererOrgs:
  - Name: Orderer
    Domain: donation.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: NGO
    Domain: ngo.donation.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: ORACLE
    Domain: oracle.donation.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1