version: '3.7'

services:
  # Orderer Service
  orderer.donation.com:
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.donation.com:9443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/donation.com/orderers/orderer.donation.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
      - 9443:9443
    networks:
      - donation

  # NGO Organization Peer
  peer0.ngo.donation.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=donation-transparency-platform_donation
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.ngo.donation.com
      - CORE_PEER_ADDRESS=peer0.ngo.donation.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ngo.donation.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ngo.donation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ngo.donation.com:7051
      - CORE_PEER_LOCALMSPID=NGOMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.ngo.donation.com:9444
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/ngo.donation.com/peers/peer0.ngo.donation.com/msp:/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - donation

  # Oracle Organization Peer  
  peer0.oracle.donation.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=donation-transparency-platform_donation
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.oracle.donation.com
      - CORE_PEER_ADDRESS=peer0.oracle.donation.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.oracle.donation.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.oracle.donation.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.oracle.donation.com:9051