version: "3.9"

################################################################################
# Donation Transparency – Minimal 2‑Org Fabric Network (Orderer + 2 Peers + CLI)
# Lead Architect Notes:
# - TLS left DISABLED for simplicity (matches your current env). Enable later for prod.
# - Make sure you generate:
#     crypto material:  cryptogen generate --config=network/crypto-config.yaml --output=network/crypto-config
#     artifacts:        configtxgen ... (genesis.block & channel tx)
# - Ensure genesis.block is a FILE at: network/channel-artifacts/genesis.block
# - Chaincode deployment & channel operations happen inside the cli container.
################################################################################

services:
  ##############################################################################
  # Orderer
  ##############################################################################
  orderer.donation.com:
    container_name: orderer.donation.com
    image: hyperledger/fabric-orderer:2.4
    restart: unless-stopped
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # TLS disabled (set to true + mount tls dir + add ORDERER_GENERAL_TLS_* for production)
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.donation.com:9443
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric        # (optional if you later mount custom orderer.yaml)
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      # Genesis block (MUST be a file, not a directory)
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      # Orderer MSP
      - ./crypto-config/ordererOrganizations/donation.com/orderers/orderer.donation.com/msp:/var/hyperledger/orderer/msp
      # (Optional) Persist orderer ledger
      - ordererdata:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
      - "9443:9443"
    networks:
      - donation

  ##############################################################################
  # NGO Peer (peer0.ngo.donation.com)
  ##############################################################################
  peer0.ngo.donation.com:
    container_name: peer0.ngo.donation.com
    image: hyperledger/fabric-peer:2.4
    restart: unless-stopped
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=donation
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.ngo.donation.com
      - CORE_PEER_ADDRESS=peer0.ngo.donation.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ngo.donation.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ngo.donation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ngo.donation.com:7051
      - CORE_PEER_LOCALMSPID=NGOMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.ngo.donation.com:9444
      # TLS disabled (match channel tools). Set CORE_PEER_TLS_ENABLED=true when enabling TLS.
      - CORE_PEER_TLS_ENABLED=false
      # Allow container-internal chaincode builds
      - CORE_CHAINCODE_EXECUTETIMEOUT=30s
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/ngo.donation.com/peers/peer0.ngo.donation.com/msp:/etc/hyperledger/fabric/msp
      # (Optional future) TLS dir if enabling TLS:
      # - ./crypto-config/peerOrganizations/ngo.donation.com/peers/peer0.ngo.donation.com/tls:/etc/hyperledger/fabric/tls
      - peer0ngodata:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
      - "9444:9444"
    networks:
      - donation
    depends_on:
      - orderer.donation.com

  ##############################################################################
  # ORACLE Peer (peer0.oracle.donation.com)
  ##############################################################################
  peer0.oracle.donation.com:
    container_name: peer0.oracle.donation.com
    image: hyperledger/fabric-peer:2.4
    restart: unless-stopped
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=donation
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.oracle.donation.com
      - CORE_PEER_ADDRESS=peer0.oracle.donation.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.oracle.donation.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.oracle.donation.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.oracle.donation.com:9051
      - CORE_PEER_LOCALMSPID=ORACLEMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.oracle.donation.com:9445
      - CORE_PEER_TLS_ENABLED=false
      - CORE_CHAINCODE_EXECUTETIMEOUT=30s
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/oracle.donation.com/peers/peer0.oracle.donation.com/msp:/etc/hyperledger/fabric/msp
      # - ./crypto-config/peerOrganizations/oracle.donation.com/peers/peer0.oracle.donation.com/tls:/etc/hyperledger/fabric/tls (enable later)
      - peer0oracledata:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "9051:9051"
      - "9445:9445"
    networks:
      - donation
    depends_on:
      - orderer.donation.com

  ##############################################################################
  # CLI (Tools) – used for channel creation, joins, chaincode lifecycle
  ##############################################################################
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    environment:
      - CORE_PEER_LOCALMSPID=NGOMSP
      - CORE_PEER_ADDRESS=peer0.ngo.donation.com:7051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer:$PATH
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      # Admin MSP for NGO (default identity)
      - ./crypto-config/peerOrganizations/ngo.donation.com/users/Admin@ngo.donation.com/msp:/etc/hyperledger/fabric/msp
      # Full crypto tree for switching org contexts
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      # Channel artifacts (genesis, channel tx, anchor updates)
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      # Chaincode source
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      # (Optional) scripts directory for automation
      - ./scripts:/scripts
    networks:
      - donation
    depends_on:
      - peer0.ngo.donation.com
      - peer0.oracle.donation.com
      - orderer.donation.com

networks:
  donation:
    name: network_donation
    driver: bridge

volumes:
  ordererdata:
  peer0ngodata:
  peer0oracledata: